updates

diff --git a/.github/workflows/automated-checks.yml b/.github/workflows/automated-checks.yml
--- a/.github/workflows/automated-checks.yml
+++ b/.github/workflows/automated-checks.yml
@@ -3,7 +3,7 @@ name: Tests
 env:
   COVERAGE_DATABASE_VERSION: mariadb:10.11
   COVERAGE_PYTHON_VERSION: 3.12
-  NODE_VERSION: 22 # [LTS] End of Life: 30 Apr 2027 (https://endoflife.date/nodejs)
+  NODE_VERSION: 24 # [LTS] End of Life: 30 Apr 2028 (https://endoflife.date/nodejs)
   REDIS_VERSION: latest
 
 on:
@@ -34,19 +34,19 @@ jobs:
 
       # Set up Python
 #      - name: Set up Python
-#        uses: actions/setup-python@v5
+#        uses: actions/setup-python@v6
 #        with:
 #          python-version-file: 'pyproject.toml' # Read the Python version from the pyproject.toml file
 
       # Set up Node.js
-      - name: Setup Node.js
-        uses: actions/setup-node@v6
-        with:
-          # https://endoflife.date/nodejs
-          node-version: ${{ env.NODE_VERSION }}
-          cache: 'npm'
-          cache-dependency-path: 'package-lock.json'
-      - run: npm install
+#      - name: Setup Node.js
+#        uses: actions/setup-node@v4
+#        with:
+#          # https://endoflife.date/nodejs
+#          node-version: ${{ env.NODE_VERSION }}
+#          cache: 'npm'
+#          cache-dependency-path: 'package-lock.json'
+#      - run: npm install
 
       - name: Run Pre Commit Checks
         uses: pre-commit/action@v3.0.1
@@ -66,29 +66,29 @@ jobs:
           - '3.11'  # [EOL] End of Life: 31 Dec 2027
           - '3.12'  # [EOL] End of Life: 31 Dec 2028
           - '3.13'  # [EOL] End of Life: 31 Oct 2029
-        # MySQL versions to test against
-        database:
-          # https://endoflife.date/mysql
-          - mysql:8.0     # [LTS] Maintained until: 30 Apr 2026
-          - mysql:8.4     # [LTS] Maintained until: 30 Apr 2032
-          # https://endoflife.date/mariadb and https://mariadb.com/kb/en/mariadb-server-release-dates/
-          - mariadb:10.6  # [LTS] Maintained until: 06 Jul 2026
-          - mariadb:10.11 # [LTS] Maintained until: 16 Feb 2028
-          - mariadb:11.4  # [LTS] Maintained until: 29 May 2029
-          - mariadb:11.8  # [LTS] Maintained until: 04 Jun 2028
-
-#    continue-on-error: ${{ matrix.python-version == '3.12' }}
-
-    # Set up services
-    services:
-      database:
-        image: ${{ matrix.database }}
-        env:
-          MYSQL_ROOT_PASSWORD: temp_password_aa_tox_tests
-          MYSQL_DATABASE: tox_allianceauth
-        ports:
-          - 3306:3306
-        options: --tmpfs /var/lib/mysql
+#        # MySQL versions to test against
+#        database:
+#          # https://endoflife.date/mysql
+#          - mysql:8.4     # [LTS] Maintained until: 30 Apr 2032
+#          - mysql:9.7     # [LTS] Maintained until: 21 Apr 2034
+#          # https://endoflife.date/mariadb and https://mariadb.com/kb/en/mariadb-server-release-dates/
+#          - mariadb:10.6  # [LTS] Maintained until: 06 Jul 2026
+#          - mariadb:10.11 # [LTS] Maintained until: 16 Feb 2028
+#          - mariadb:11.4  # [LTS] Maintained until: 29 May 2029
+#          - mariadb:11.8  # [LTS] Maintained until: 04 Jun 2028
+#
+##    continue-on-error: ${{ matrix.python-version == '3.12' }}
+#
+#    # Set up services
+#    services:
+#      database:
+#        image: ${{ matrix.database }}
+#        env:
+#          MYSQL_ROOT_PASSWORD: temp_password_aa_tox_tests
+#          MYSQL_DATABASE: tox_allianceauth
+#        ports:
+#          - 3306:3306
+#        options: --tmpfs /var/lib/mysql
 
     steps:
       # Checkout the repository
@@ -107,7 +107,7 @@ jobs:
 
       # Set up Python
       - name: Setup Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v5
+        uses: actions/setup-python@v6
         with:
           python-version: ${{ matrix.python-version }}
 
@@ -119,38 +119,39 @@ jobs:
 
       # Run Tox with the specified environment
       - name: Run Tox
-        env:
-          TOX_ENV: allianceauth-latest
-          DB_HOST: 127.0.0.1
-          DB_USER: root
-          DB_PASSWORD: temp_password_aa_tox_tests
-        run: tox -v -e ${{ env.TOX_ENV }}
+#        env:
+#          TOX_ENV: allianceauth-latest
+#          DB_HOST: 127.0.0.1
+#          DB_USER: root
+#          DB_PASSWORD: temp_password_aa_tox_tests
+#        run: tox -v -e ${{ env.TOX_ENV }}
+        run: tox -v
 
       # Upload coverage to Codecov
-      - name: Upload Coverage
-        if: ${{
-              (
-                github.event_name == 'pull_request'
-                || (
-                  github.event_name == 'push'
-                  && github.ref == 'refs/heads/master'
-                )
-              )
-              && (
-                matrix.python-version == env.COVERAGE_PYTHON_VERSION
-                && matrix.database == env.COVERAGE_DATABASE_VERSION
-              )
-            }}
-        uses: codecov/codecov-action@v6
-        with:
-#          token: ${{ secrets.CODECOV_TOKEN }}
-          files: coverage.xml # optional
-#          flags: unittests # optional
-#          name: codecov-umbrella # optional
-#          fail_ci_if_error: true # optional (default = false)
-          verbose: true # optional (default = false)
-        env:
-          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+#      - name: Upload Coverage
+#        if: ${{
+#              (
+#                github.event_name == 'pull_request'
+#                || (
+#                  github.event_name == 'push'
+#                  && github.ref == 'refs/heads/master'
+#                )
+#              )
+#              && (
+#                matrix.python-version == env.COVERAGE_PYTHON_VERSION
+#                && matrix.database == env.COVERAGE_DATABASE_VERSION
+#              )
+#            }}
+#        uses: codecov/codecov-action@v5
+#        with:
+##          token: ${{ secrets.CODECOV_TOKEN }}
+#          files: coverage.xml # optional
+##          flags: unittests # optional
+##          name: codecov-umbrella # optional
+##          fail_ci_if_error: true # optional (default = false)
+#          verbose: true # optional (default = false)
+#        env:
+#          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
 
   # Run PyPi Build Test
   pypi-build-test:
@@ -165,7 +166,7 @@ jobs:
 
       # Set up Python
       - name: Set up Python
-        uses: actions/setup-python@v5
+        uses: actions/setup-python@v6
         with:
           python-version-file: 'pyproject.toml' # Read the Python version from the pyproject.toml file
 
